/* Authentication */

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";

/* Accounts */

export const CREATE_ACCOUNT_START = "CREATE_ACCOUNT_START";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAIL = "CREATE_ACCOUNT_FAIL";

export const FETCH_ACCOUNTS_START = "FETCH_ACCOUNTS_START";
export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_FAIL = "FETCH_ACCOUNTS_FAIL";

export const UPDATE_ACCOUNT_START = "UPDATE_ACCOUNT_START";
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";
export const UPDATE_ACCOUNT_FAIL = "UPDATE_ACCOUNT_FAIL";

export const DELETE_ACCOUNT_START = "DELETE_ACCOUNT_START";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL";

export const SET_ACCOUNT_TO_EDIT = "SET_ACCOUNT_TO_EDIT";
export const CLEAR_ACCOUNT_TO_EDIT = "CLEAR_ACCOUNT_TO_EDIT";

export const CLEAR_ACCOUNTS_ERROR = "CLEAR_ACCOUNTS_ERROR";

/* Categories */

export const CREATE_CATEGORY_START = "CREATE_CATEGORY_START";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";

export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

export const UPDATE_CATEGORY_START = "UPDATE_CATEGORY_START";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";

export const SET_CATEGORY_TO_EDIT = "SET_CATEGORY_TO_EDIT";
export const CLEAR_CATEGORY_TO_EDIT = "CLEAR_CATEGORY_TO_EDIT";

export const CLEAR_CATEGORIES_ERROR = "CLEAR_CATEGORIES_ERROR";

/* Transactions */

export const CREATE_TRANSACTION_START = "CREATE_TRANSACTION_START";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAIL = "CREATE_TRANSACTION_FAIL";

export const FETCH_TRANSACTIONS_BY_DATE_START =
  "FETCH_TRANSACTIONS_BY_DATE_START";
export const FETCH_TRANSACTIONS_BY_DATE_SUCCESS =
  "FETCH_TRANSACTIONS_BY_DATE_SUCCESS";
export const FETCH_TRANSACTIONS_BY_DATE_FAIL =
  "FETCH_TRANSACTIONS_BY_DATE_FAIL";

export const UPDATE_TRANSACTION_START = "UPDATE_TRANSACTION_START";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_FAIL = "UPDATE_TRANSACTION_FAIL";

export const DELETE_TRANSACTION_START = "DELETE_TRANSACTION_START";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAIL = "DELETE_TRANSACTION_FAIL";

export const SET_TRANSACTION_TO_EDIT = "SET_TRANSACTION_TO_EDIT";
export const CLEAR_TRANSACTION_TO_EDIT = "CLEAR_TRANSACTION_TO_EDIT";

export const CLEAR_TRANSACTIONS_ERROR = "CLEAR_TRANSACTIONS_ERROR";

/* Home */

export const GET_OVERALL_BALANCE_START = "GET_OVERALL_BALANCE_START";
export const GET_OVERALL_BALANCE_SUCCESS = "GET_OVERALL_BALANCE_SUCCESS";
export const GET_OVERALL_BALANCE_FAIL = "GET_OVERALL_BALANCE_FAIL";

export const SET_SELECTED_DATE = "SET_SELECTED_DATE";

/* Notifications */

export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const DISMISS_NOTIFICATION = "DISMISS_NOTIFICATION";
